### ISSUE TITLE
Some of our Users are getting Error Code 5

### ISSUE THREAD

**Issue by ForestRingGames** [anjlab/android-inapp-billing-v3#361]
Do you want to request a **feature** or report a **bug**?
-Bug

What is the current behavior?
-Some of our Users are getting error code 5 when trying to purchase something. We have a user that can check test builds for us. He has a Samsung S8 and Android 8.0. We don't know the details about the other users yet.

This function is being called 
```
    public static void purchase(String productIdentifier)
    {
        GameLog.i("[Java][InAppPurchase] purchase:" + productIdentifier);
        billingProcessor.purchase(GameApplication.getActivity(), productIdentifier);
    }
```

Then the user is shown this error:

![image](https://user-images.githubusercontent.com/21338444/44836481-5f7ce700-ac37-11e8-9bc0-7a6e559ca430.png)

Sorry about the German, it means something like: "The requested article can not be purchased."

It does work on my test devices Samsung S5; Android 6.0.1 and Samsung S6; Android 7.0.0

If the current behavior is a bug, **please provide the steps to reproduce** and if possible a minimal demo of the problem or a code snippet.
Don't forget to mention:
- which version of library you use

We're using Android Studio with this in our build.gradle
`implementation 'com.anjlab.android.iab.v3:library:1.0.44'`

- was it working in previous versions?
        -it is working on my own test device right now, but not on a users.
- do you use fragments or not
     -no
- how do you instanciate `BillingProcessor` (singleton or not)
     -We create a single instance:

```
        InAppPurchase.setBillingProcessor(new BillingProcessor(this, "XXX", this));
        InAppPurchase.setInAppSKUList(Utils.loadStringLinesFromAsset("InAppProducts.txt"));
    ```

- which device/OS version do you use for testing (or its an emulator)
     -It doesn't work on a Samsung S8; Android 8.0.0
- have you uploaded it to Google Play or not (if yes, when which channel: Prod/Beta/Alpha)  
      -Yes, it's live on the App Store and we did test Beta and Prod
      -In case you want to test it: 
               Beta: https://play.google.com/apps/testing/com.forestringgames.apps.towerduel
               Prod: https://play.google.com/apps/publish/?account=7938476559309985542#ManageReleasesPlace:p=com.forestringgames.apps.towerduel&appid=4974153108349641553
              -The game will force you to play the tutorial. You can skip it by playing through the very first mission ( will take like 2 minutes) and then pressing at the bottom bar 5x Cards --> 5x Shop 

- do you test with real products, or with a testing onces (e.g. `android.test.purchased`)
     -Real Products

**Comment by Defskidrow** [comment]
Hast du mal geguckt ob der Artikel aktiv ist?

**Comment by ForestRingGames** [comment]
@Defskidrow It seems like we fixed this at init:

```
bp = BillingProcessor.newBillingProcessor(this, "YOUR LICENSE KEY FROM GOOGLE PLAY CONSOLE HERE", this); // doesn't bind
bp.initialize(); // binds
```

This is from the documentation and it says you should do if you encounter "very rare race conditions". As it seems like...it's not so rare.

**Comment by alneil** [comment]
resolved yet?

**Comment by GauravCreed** [comment]
@Defskidrow 

Not yet, issue is still there 

errorCode : 5
getMessage : Client is already in the process of connecting to billing service.

I didn't know why this is happening.
