### ISSUE TITLE
onBillingError called after successful purchase

### ISSUE THREAD

**Issue by stefanhenze** [anjlab/android-inapp-billing-v3#94]
I found at least two instances where a purchase was successful, and the library still called `onBillingError`. Here are the two examples:

#### JSON exception ####
```
D/iabv3﹕ resultCode = -1, responseCode = 0
E/iabv3﹕ org.json.JSONException: No value for orderId
E/AccountManagementActivity﹕ [ERROR] onBillingError, errorCode: 110
```

#### Re-subscribe after canceling subscription ####
```
D/iabv3﹕ resultCode = -1, responseCode = 0
E/iabv3﹕ Payload mismatch: subs:890d420a-d51f-4d1c-a8bb-c17f8655f517 != subs:b7c9e146-202b-453f-88eb-3e6ad58ec440
E/AccountManagementActivity﹕ [ERROR] onBillingError, errorCode: 102
```

How are these situations supposed to be handled? If I understand it correctly, the purchases went through in both cases, but the library tells the app that they did not.

**Comment by achuinard** [comment]
Need dev to merge https://github.com/anjlab/android-inapp-billing-v3/pull/99

**Comment by niko001** [comment]
Re-subscribing after canceling a subscription still fails for me using `v1.0.27` with the same error mentioned by @stefanhenze:

    D/iabv3﹕ resultCode = -1, responseCode = 0   
    E/iabv3﹕ Payload mismatch: subs:26001cb3-3471-46ac-ba7b-426e41xxxxxx != subs:02c85537-d855-4b7f-95be-65c5ecxxxxxx

**Comment by serggl** [comment]
@niko001 confirming this issue. Working on a fix

**Comment by serggl** [comment]
must be fixed with #137

**Comment by serggl** [comment]
can someone confirm this issue is fixed?

**Comment by Semmix** [comment]
The issue still persists, i am trying to solve it myself, if i succeed, i will post the code here.

**Comment by mtrakal** [comment]
On latest version (`com.anjlab.android.iab.v3:library:1.0.31`) I receive:

```
03-08 11:29:49.996 18891-18891/com.my.app D/iabv3: resultCode = -1, responseCode = 0
03-08 11:29:49.996 18891-18891/com.my.app E/iabv3: Payload mismatch: subs:v3_2_advanced_monthly != subs:6e172bea-d331-499d-xxxx-9db792a0686c
```

I had subscription before, cancel subscription and later subscribe.

**Comment by 9mm** [comment]
Same here, Ordering after cancelling results in payload mismatch.

**Comment by alfredr** [comment]
I don't understand what this check is supposed to do. Isn't this field arbitrary?

**Comment by 9mm** [comment]
Another very odd thing is that `autoRenewing: false` appears to be set on an active subscription that is created after a subscription is cancelled. It properly displays `true` if the subscription has never been cancelled though.

**Comment by DarkRockman** [comment]
Same here, using v 1.0.31 Im getting error code 102 after I try to subscribe again to a cancelled subscription.

**Comment by david2410** [comment]
I am also getting error 110 after every 2nd purchase.

**Comment by maan-smith** [comment]
@stefanhenze I am still facing this issue did you get any work around?

**Comment by HD-AD** [comment]
I'm also getting onBillingError after I successfully purchased??? I'm only getting onProductPurchased after the purchase is complete and I try to purchase again?

**Comment by craigcoles** [comment]
I am also getting an `Error: Purchase or subscribe failed with error: 110`. This is happening on every purchase. If I then `restorePurchases` it comes back with the subscription.

**Comment by YarKaras** [comment]
I have this problem too.

**Comment by majinman** [comment]
I get Same problem in 2018. I have to quit using this library.

**Comment by SashaKhyzhun** [comment]
The same problem 22.01.2019

**Comment by HBiSoft** [comment]
It's been 4 years since this issue was opened. I think it's save to say that it's not going to be resolved.
